### ISSUE TITLE
[Bug]无法启动最新快照

### ISSUE THREAD

**Issue by Haocen2004** [TISUnion/MCDaemon-go#2]
MCDaemon版本：1.0 - 2.1 Windows 和 Linux 均存在
Minecraft版本：19w03c
描述：弹出加载界面后几秒钟崩溃，minecraft服务器无文件生成
log：
MCDaemon无记录
Minecraft：
```
[20:17:43] [main/FATAL]: Failed to start the minecraft server
joptsimple.UnrecognizedOptionException: D is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108) ~[server.jar:?]
	at joptsimple.OptionParser.validateOptionCharacters(OptionParser.java:633) ~[server.jar:?]
	at joptsimple.OptionParser.handleShortOptionCluster(OptionParser.java:528) ~[server.jar:?]
	at joptsimple.OptionParser.handleShortOptionToken(OptionParser.java:523) ~[server.jar:?]
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:59) ~[server.jar:?]
	at joptsimple.OptionParser.parse(OptionParser.java:396) ~[server.jar:?]
	at net.minecraft.server.MinecraftServer.main(SourceFile:881) [server.jar:?]
```
log里面只有这些

**Comment by kafuuchino-desu** [comment]
启动的jvm参数错误了 @lightbrotherV 你来看看

**Comment by lightbrotherV** [comment]
快照暂时不支持吧，目前就支持正式版，快照改动太频繁，无法都支持

**Comment by lightbrotherV** [comment]
该问题已修复，现在已支持快照版本的启动
